# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  
  client-id:
    description: 'Azure Service Principle Client Id'
    required: true
    
  tenant-id:
    description: 'Azure Active Directory Tenant Id'
    required: true
    
  subscription-id:  
    description: 'Azure Subscription Id'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
    - ${{ inputs.client-id }}
    - ${{ inputs.tenant-id }}
    - ${{ inputs.subscription-id }}